import sys

file_path = '/home/t4riq/wolf_prowler/wolf-networking/wolf_net/src/swarm.rs'
with open(file_path, 'r') as f:
    lines = f.readlines()

new_lines = []
skip_until = -1
for i, line in enumerate(lines):
    if i == 593: # line 594 (0-indexed)
        new_lines.append('                                        SwarmEvent::ConnectionEstablished { peer_id, endpoint, .. } => {\n')
        new_lines.append('                                            // Network protection check\n')
        new_lines.append('                                            let ip_addr = match &endpoint {\n')
        new_lines.append('                                                libp2p::core::ConnectedPoint::Listener { send_back_addr, .. } => {\n')
        new_lines.append('                                                    send_back_addr.iter().find_map(|proto| {\n')
        new_lines.append('                                                        match proto {\n')
        new_lines.append('                                                            libp2p::multiaddr::Protocol::Ip4(ip) => Some(std::net::IpAddr::V4(ip)),\n')
        new_lines.append('                                                            libp2p::multiaddr::Protocol::Ip6(ip) => Some(std::net::IpAddr::V6(ip)),\n')
        new_lines.append('                                                            _ => None,\n')
        new_lines.append('                                                        }\n')
        new_lines.append('                                                    })\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                                libp2p::core::ConnectedPoint::Dialer { address, .. } => {\n')
        new_lines.append('                                                    address.iter().find_map(|proto| {\n')
        new_lines.append('                                                        match proto {\n')
        new_lines.append('                                                            libp2p::multiaddr::Protocol::Ip4(ip) => Some(std::net::IpAddr::V4(ip)),\n')
        new_lines.append('                                                            libp2p::multiaddr::Protocol::Ip6(ip) => Some(std::net::IpAddr::V6(ip)),\n')
        new_lines.append('                                                            _ => None,\n')
        new_lines.append('                                                        }\n')
        new_lines.append('                                                    })\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                            };\n')
        new_lines.append('\n')
        new_lines.append('                                            let decision = {\n')
        new_lines.append('                                                let mut np = network_protection_clone.lock().await;\n')
        new_lines.append('                                                np.check_incoming_connection(&peer_id, ip_addr).await\n')
        new_lines.append('                                            };\n')
        new_lines.append('\n')
        new_lines.append('                                            if !decision.allowed {\n')
        new_lines.append('                                                warn!("🔥 Network protection blocked connection from {}: {}", peer_id, decision.reason);\n')
        new_lines.append('                                                if let Some(reporter) = &reputation_reporter {\n')
        new_lines.append('                                                    reporter.report_event(\n')
        new_lines.append('                                                        &peer_id.to_string(),\n')
        new_lines.append('                                                        "Security",\n')
        new_lines.append('                                                        -0.2,\n')
        new_lines.append('                                                        format!("Connection blocked: {}", decision.reason)\n')
        new_lines.append('                                                    ).await;\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                                let _ = swarm.disconnect_peer_id(peer_id);\n')
        new_lines.append('                                                if let Some(sender) = &security_sender {\n')
        new_lines.append('                                                    let event = SecurityEvent::new(\n')
        new_lines.append('                                                        SecurityEventType::Other("ConnectionEstablished".to_string()),\n')
        new_lines.append('                                                        SecuritySeverity::Medium,\n')
        new_lines.append('                                                        format!("Network protection blocked peer {}", peer_id),\n')
        new_lines.append('                                                    ).with_peer(peer_id.to_string());\n')
        new_lines.append('                                                    let _ = sender.send(event);\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                                continue;\n')
        new_lines.append('                                            }\n')
        new_lines.append('\n')
        new_lines.append('                                            // Firewall check\n')
        new_lines.append('                                            let firewall_allowed = {\n')
        new_lines.append('                                                let fw = firewall_clone.read().await;\n')
        new_lines.append('                                                fw.check_access(\n')
        new_lines.append('                                                    &RuleTarget::PeerId(peer_id.to_string()),\n')
        new_lines.append('                                                    &Protocol::Any,\n')
        new_lines.append('                                                    &TrafficDirection::Inbound,\n')
        new_lines.append('                                                )\n')
        new_lines.append('                                            };\n')
        new_lines.append('\n')
        new_lines.append('                                            if !firewall_allowed {\n')
        new_lines.append('                                                if let Some(reporter) = &reputation_reporter {\n')
        new_lines.append('                                                    reporter.report_event(\n')
        new_lines.append('                                                        &peer_id.to_string(),\n')
        new_lines.append('                                                        "Security",\n')
        new_lines.append('                                                        -0.15,\n')
        new_lines.append('                                                        "Firewall blocked incoming connection".to_string()\n')
        new_lines.append('                                                    ).await;\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                                let _ = swarm.disconnect_peer_id(peer_id);\n')
        new_lines.append('                                                if let Some(sender) = &security_sender {\n')
        new_lines.append('                                                    let event = SecurityEvent::new(\n')
        new_lines.append('                                                        SecurityEventType::Other("ConnectionEstablished".to_string()),\n')
        new_lines.append('                                                        SecuritySeverity::Medium,\n')
        new_lines.append('                                                        format!("Firewall blocked peer {}", peer_id),\n')
        new_lines.append('                                                    ).with_peer(peer_id.to_string());\n')
        new_lines.append('                                                    let _ = sender.send(event);\n')
        new_lines.append('                                                }\n')
        new_lines.append('                                                continue;\n')
        new_lines.append('                                            }\n')
        skip_until = 656 # Skip until line 657 (0-indexed)
    elif i <= skip_until:
        continue
    elif i == 671: # line 672 (original network_protection.record_connection_success)
        new_lines.append('                                             // Record successful connection\n')
        new_lines.append('                                             {\n')
        new_lines.append('                                                 let mut np = network_protection_clone.lock().await;\n')
        new_lines.append('                                                 np.record_connection_success(&peer_id).await;\n')
        new_lines.append('                                             }\n')
        skip_until = 672
    else:
        new_lines.append(line)

with open(file_path, 'w') as f:
    f.writelines(new_lines)
