version: '3.8'

services:
  # Node 1: Seed / Bootstrapper
  wolf_node_1:
    image: wolf_prowler:latest
    container_name: wolf_node_1
    build: .
    environment:
      - RUST_LOG=info
      - WOLF_HEADLESS=true
      - WOLF_P2P_PORT=3001
    ports:
      - "3001:3001"
    networks:
      - wolf_net
    volumes:
      - ./wolf_data/node1:/data

  # Node 2: Peer
  wolf_node_2:
    image: wolf_prowler:latest
    container_name: wolf_node_2
    build: .
    environment:
      - RUST_LOG=info
      - WOLF_HEADLESS=true
      - WOLF_P2P_PORT=3002
      - WOLF_BOOTSTRAP_PEERS=/dns4/wolf_node_1/tcp/3001
    ports:
      - "3002:3002"
    networks:
      - wolf_net
    depends_on:
      - wolf_node_1
    volumes:
      - ./wolf_data/node2:/data

  # Node 3: Peer
  wolf_node_3:
    image: wolf_prowler:latest
    container_name: wolf_node_3
    build: .
    environment:
      - RUST_LOG=info
      - WOLF_HEADLESS=true
      - WOLF_P2P_PORT=3003
      - WOLF_BOOTSTRAP_PEERS=/dns4/wolf_node_1/tcp/3001
    ports:
      - "3003:3003"
    networks:
      - wolf_net
    depends_on:
      - wolf_node_1
    volumes:
      - ./wolf_data/node3:/data

  # Kali Linux Monitoring Node
  kali_monitor:
    image: kalilinux/kali-rolling
    container_name: kali_monitor
    tty: true
    stdin_open: true
    privileged: true # Required for sniffing
    networks:
      - wolf_net
    command: /bin/bash -c "apt-get update && apt-get install -y iproute2 iputils-ping tcpdump net-tools nmap && /bin/bash"

networks:
  wolf_net:
    driver: bridge
